chore: update build rc command to push and NOT build (#51)
* chore: push and add versioning

* chore: remove EAS build

diff --git a/.github/workflows/build-rc.yml b/.github/workflows/build-rc.yml
--- a/.github/workflows/build-rc.yml
+++ b/.github/workflows/build-rc.yml
@@ -43,6 +43,10 @@ jobs:
                   app-id: ${{ vars.RELEASE_BOT_APP_ID }}
                   private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
 
+            - name: Parse version
+              id: version
+              uses: ./.github/parse-version
+
             - name: Checkout repository
               uses: actions/checkout@v4
               with:
@@ -60,6 +64,7 @@ jobs:
                   git config --global user.email '${{ vars.RELEASE_BOT_USER_ID }}+awana-release-bot[bot]@users.noreply.github.com'
                   git add release-notes/closed-issues-v*.md release-notes/closed-prs-v*.md
                   git commit -m "docs: add cherry pick commits to release notes"
+                  git push origin rc/v${{ steps.version.outputs.releaseShort }}
 
             - name: Setup Node.js
               uses: actions/setup-node@v4
@@ -81,14 +86,16 @@ jobs:
               env:
                   EAS_PROJECT_URL: ${{ vars.EAS_PROJECT_URL }}
               run: |
-                  build_id=$( eas build --platform android --profile release-candidate --json --non-interactive --no-wait | jq '.[0].id' --raw-output )
-                  if [ -z "$build_id" ]; then
-                    echo "Unable to get build ID"
-                    exit 1
-                  fi
                   echo "Build ID: $build_id"
-                  eas_build_url="$EAS_PROJECT_URL/builds/$build_id"
-                  echo "eas_build_url=$eas_build_url" >> $GITHUB_OUTPUT
+              #   removing for now so we dont have unnecessart builds
+              #   build_id=$( eas build --platform android --profile release-candidate --json --non-interactive --no-wait | jq '.[0].id' --raw-output )
+              #   if [ -z "$build_id" ]; then
+              #     echo "Unable to get build ID"
+              #     exit 1
+              #   fi
+              #   echo "Build ID: $build_id"
+              #   eas_build_url="$EAS_PROJECT_URL/builds/$build_id"
+              #   echo "eas_build_url=$eas_build_url" >> $GITHUB_OUTPUT
 
     comment:
         name: Comment
