add checks for release version

diff --git a/.github/workflows/check-release-branch.yml b/.github/workflows/check-release-branch.yml
--- a/.github/workflows/check-release-branch.yml
+++ b/.github/workflows/check-release-branch.yml
@@ -10,7 +10,7 @@ on:
             - 'release/**'
 
 jobs:
-    check_branch:
+    check_release_branch:
         name: No Commits
         runs-on: ubuntu-latest
 
@@ -39,19 +39,54 @@ jobs:
                     exit 1
                   fi
 
-    assert_from_rc_branch:
-        name: Only allow pull request from RC branch
+    check_rc_branch:
+        name: Check RC branch
         runs-on: ubuntu-latest
 
         steps:
             - name: Checkout repository
               uses: actions/checkout@v4
 
+            - name: Get branch name of the PR
+              id: pr_branch_name
+              run: |
+                  pr_branch_name=$(git branch --show-current)
+                  echo "result=$PR_BRANCH_NAME" >> $GITHUB_OUTPUT
+
             - name: Assert pull request is created from a RC branch
+              env:
+                  PR_BRANCH_NAME: ${{ steps.pr_branch_name.outputs.result }}
               run: |
                   set -x
-                  PR_BRANCH_NAME=$(git branch --show-current)
                   if [ $PR_BRANCH_NAME != rc/* ]; then
                       echo "Pull request to release branch must come from RC branch"
+                      exit 1
+                  fi
+
+            - name: Parse version
+              id: version
+              uses: ./.github/parse-version
+
+            - name: Assert release version is not pre-release
+              env:
+                  RELEASE_VERSION: ${{ steps.version.outputs.releaseVersion }}
+              run: |
+                  set -x
+                  echo $RELEASE_VERSION
+                  if [ $RELEASE_VERSION = *-pre ]; then
+                    echo "Release version cannot be pre-release"
+                    exit 1
+                  fi
+
+            - name: Assert release version matches RC branch name
+              env:
+                  PR_BRANCH_NAME: ${{ steps.pr_branch_name.outputs.result }}
+                  RELEASE_SHORT: ${{ steps.version.outputs.releaseShort }}
+              run: |
+                  set -x
+                  echo $PR_BRANCH_NAME
+                  echo $RELEASE_SHORT
+                  if [ $PR_BRANCH_NAME != "rc/v$RELEASE_SHORT" ]; then
+                      echo "Release version does not match RC branch"
                       exit 1
                   fi
